#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

import math


FFT_SIZE = 64
RADIX = 4
TWIDDLE_SHIFT = 15
STAGES = (16, 4, 1)


def to_q15(value):
    """Match fixed-point conversion: truncate toward zero, then saturate."""
    scaled = int(value * (1 << TWIDDLE_SHIFT))
    return max(-32768, min(32767, scaled))


def make_table(vectorization, exponent):
    stage_size = FFT_SIZE // vectorization
    table_size = stage_size // RADIX
    return [
        (
            to_q15(math.cos(-2.0 * math.pi * exponent * i / stage_size)),
            to_q15(math.sin(-2.0 * math.pi * exponent * i / stage_size)),
        )
        for i in range(table_size)
    ]


def format_table(name, values):
    entries = [f"{{{real}, {imag}}}" for real, imag in values]
    lines = []
    for offset in range(0, len(entries), 4):
        suffix = "," if offset + 4 < len(entries) else ""
        lines.append("    " + ", ".join(entries[offset : offset + 4]) + suffix)
    body = "\n".join(lines)
    return (
        f"alignas(aie::vector_decl_align) static const cint16 {name}[] = {{\n"
        f"{body}}};"
    )


def main():
    print("// Generated by generate_twiddles.py. Do not edit manually.")
    print("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    print()
    print("#pragma once")
    print()

    # Radix-4 expects rotation rates in the argument order T2, T1, T3.
    for stage, vectorization in enumerate(STAGES):
        for suffix, exponent in (("Tw2", 2), ("Tw1", 1), ("Tw3", 3)):
            print(format_table(f"kStage{stage}{suffix}", make_table(vectorization, exponent)))
        if stage != len(STAGES) - 1:
            print()


if __name__ == "__main__":
    main()
