/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bfloat16_to_float32.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c7c97b73cca24f7591ec41a3d18045f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/bfloat16_to_float32.h>
// pydoc.h is automatically generated in the build directory
#include <bfloat16_to_float32_pydoc.h>

void bind_bfloat16_to_float32(py::module& m)
{

    using bfloat16_to_float32    = gr::mlir_aie::bfloat16_to_float32;


    py::class_<bfloat16_to_float32, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bfloat16_to_float32>>(m, "bfloat16_to_float32", D(bfloat16_to_float32))

        .def(py::init(&bfloat16_to_float32::make),
           D(bfloat16_to_float32,make)
        )
        



        ;




}








