/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cbfloat_to_complex64.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73af44e665b92e8611da29876b3b2ed7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/cbfloat_to_complex64.h>
// pydoc.h is automatically generated in the build directory
#include <cbfloat_to_complex64_pydoc.h>

void bind_cbfloat_to_complex64(py::module& m)
{

    using cbfloat_to_complex64    = gr::mlir_aie::cbfloat_to_complex64;


    py::class_<cbfloat_to_complex64, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cbfloat_to_complex64>>(m, "cbfloat_to_complex64", D(cbfloat_to_complex64))

        .def(py::init(&cbfloat_to_complex64::make),
           D(cbfloat_to_complex64,make)
        )
        



        ;




}








