/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cint32_to_complex64.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(87d7b543eda166efe794040815d37e78)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/cint32_to_complex64.h>
// pydoc.h is automatically generated in the build directory
#include <cint32_to_complex64_pydoc.h>

void bind_cint32_to_complex64(py::module& m)
{

    using cint32_to_complex64    = gr::mlir_aie::cint32_to_complex64;


    py::class_<cint32_to_complex64, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cint32_to_complex64>>(m, "cint32_to_complex64", D(cint32_to_complex64))

        .def(py::init(&cint32_to_complex64::make),
           D(cint32_to_complex64,make),
           py::arg("integer_bits"),
           py::arg("fractional_bits")
        )
        



        ;




}






