/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(complex64_to_cint32.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(81fa3d574afaab59df4cc41d51f97eaf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/complex64_to_cint32.h>
// pydoc.h is automatically generated in the build directory
#include <complex64_to_cint32_pydoc.h>

void bind_complex64_to_cint32(py::module& m)
{

    using complex64_to_cint32    = gr::mlir_aie::complex64_to_cint32;


    py::class_<complex64_to_cint32, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<complex64_to_cint32>>(m, "complex64_to_cint32", D(complex64_to_cint32))

        .def(py::init(&complex64_to_cint32::make),
           D(complex64_to_cint32,make),
           py::arg("integer_bits"),
           py::arg("fractional_bits"),
           py::arg("safe") = false
        )
        



        ;




}






