/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(complex64_to_cbfloat.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6a3764dacb3691a9dc7b4b6df2670c1d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/complex64_to_cbfloat.h>
// pydoc.h is automatically generated in the build directory
#include <complex64_to_cbfloat_pydoc.h>

void bind_complex64_to_cbfloat(py::module& m)
{

    using complex64_to_cbfloat    = gr::mlir_aie::complex64_to_cbfloat;


    py::class_<complex64_to_cbfloat, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<complex64_to_cbfloat>>(m, "complex64_to_cbfloat", D(complex64_to_cbfloat))

        .def(py::init(&complex64_to_cbfloat::make),
           D(complex64_to_cbfloat,make)
        )
        



        ;




}








