/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(float32_to_bfloat16.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(056747cbd9061a7c74b1b19d2b94abf3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/float32_to_bfloat16.h>
// pydoc.h is automatically generated in the build directory
#include <float32_to_bfloat16_pydoc.h>

void bind_float32_to_bfloat16(py::module& m)
{

    using float32_to_bfloat16    = gr::mlir_aie::float32_to_bfloat16;


    py::class_<float32_to_bfloat16, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<float32_to_bfloat16>>(m, "float32_to_bfloat16", D(float32_to_bfloat16))

        .def(py::init(&float32_to_bfloat16::make),
           D(float32_to_bfloat16,make)
        )
        



        ;




}








