/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(float32_to_int32_Q.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(812407ec8842f0a84fc7b5e9b4452ec0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/float32_to_int32_Q.h>
// pydoc.h is automatically generated in the build directory
#include <float32_to_int32_Q_pydoc.h>

void bind_float32_to_int32_Q(py::module& m)
{

    using float32_to_int32_Q    = gr::mlir_aie::float32_to_int32_Q;


    py::class_<float32_to_int32_Q, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<float32_to_int32_Q>>(m, "float32_to_int32_Q", D(float32_to_int32_Q))

        .def(py::init(&float32_to_int32_Q::make),
           D(float32_to_int32_Q,make),
           py::arg("integer_bits"),
           py::arg("fractional_bits"),
           py::arg("safe") = false
        )
        



        ;




}






