/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(int32_Q_to_float32.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(82b6b5a070eecbd77f30f47a6f290510)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/int32_Q_to_float32.h>
// pydoc.h is automatically generated in the build directory
#include <int32_Q_to_float32_pydoc.h>

void bind_int32_Q_to_float32(py::module& m)
{

    using int32_Q_to_float32    = gr::mlir_aie::int32_Q_to_float32;


    py::class_<int32_Q_to_float32, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<int32_Q_to_float32>>(m, "int32_Q_to_float32", D(int32_Q_to_float32))

        .def(py::init(&int32_Q_to_float32::make),
           D(int32_Q_to_float32,make),
           py::arg("integer_bits"),
           py::arg("fractional_bits")
        )
        



        ;




}






