/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mlir_aie_cpp_equalizer_test.h) */
/* BINDTOOL_HEADER_FILE_HASH(38e0741135f68874a13abb9f80c024c1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/mlir_aie_cpp_equalizer_test.h>
// pydoc.h is automatically generated in the build directory
#include <mlir_aie_cpp_equalizer_test_pydoc.h>

void bind_mlir_aie_cpp_equalizer_test(py::module& m)
{

    using mlir_aie_cpp_equalizer_test = gr::mlir_aie::mlir_aie_cpp_equalizer_test;


    py::class_<mlir_aie_cpp_equalizer_test,
               gr::block,
               gr::basic_block,
               std::shared_ptr<mlir_aie_cpp_equalizer_test>>(
        m, "mlir_aie_cpp_equalizer_test", D(mlir_aie_cpp_equalizer_test))

        .def(py::init(&mlir_aie_cpp_equalizer_test::make),
             D(mlir_aie_cpp_equalizer_test, make),
             py::arg("path_xclbin") = "build/final.xclbin",
             py::arg("path_insts_bin") = "build/insts.bin",
             py::arg("kernel_name") = "MLIR_AIE",
             py::arg("VECTOR_SIZE") = 4096,
             py::arg("nominal_frequency") = 2.417e9)

        .def("set_nominal_frequency",
             &mlir_aie_cpp_equalizer_test::set_nominal_frequency)
        .def("nominal_frequency", &mlir_aie_cpp_equalizer_test::nominal_frequency)


        ;
}
