/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mlir_aie_cpp_80211_magsq_and_div.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9f8ef0dd68d9d5c370778c89fcf4d9e5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/mlir_aie_cpp_80211_magsq_and_div.h>
// pydoc.h is automatically generated in the build directory
#include <mlir_aie_cpp_80211_magsq_and_div_pydoc.h>

void bind_mlir_aie_cpp_80211_magsq_and_div(py::module& m)
{

    using mlir_aie_cpp_80211_magsq_and_div    = gr::mlir_aie::mlir_aie_cpp_80211_magsq_and_div;


    py::class_<mlir_aie_cpp_80211_magsq_and_div, gr::block, gr::basic_block,
        std::shared_ptr<mlir_aie_cpp_80211_magsq_and_div>>(m, "mlir_aie_cpp_80211_magsq_and_div", D(mlir_aie_cpp_80211_magsq_and_div))

        .def(py::init(&mlir_aie_cpp_80211_magsq_and_div::make),
           D(mlir_aie_cpp_80211_magsq_and_div,make)
        )
        



        ;




}








