/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mlir_aie_cpp_int32_source_1arg.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8cc2cc1797886bfd16dfc9011b08cdc0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/mlir_aie_cpp_int32_source_1arg.h>
// pydoc.h is automatically generated in the build directory
#include <mlir_aie_cpp_int32_source_1arg_pydoc.h>

void bind_mlir_aie_cpp_int32_source_1arg(py::module& m)
{

    using mlir_aie_cpp_int32_source_1arg    = gr::mlir_aie::mlir_aie_cpp_int32_source_1arg;


    py::class_<mlir_aie_cpp_int32_source_1arg, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<mlir_aie_cpp_int32_source_1arg>>(m, "mlir_aie_cpp_int32_source_1arg", D(mlir_aie_cpp_int32_source_1arg))

        .def(py::init(&mlir_aie_cpp_int32_source_1arg::make),
           D(mlir_aie_cpp_int32_source_1arg,make)
        )
        



        ;




}







