/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mlir_aie_cpp_uint8.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(710aeac58acb9ebccc8f836e57af0860)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/mlir_aie_cpp_uint8.h>
// pydoc.h is automatically generated in the build directory
#include <mlir_aie_cpp_uint8_pydoc.h>

void bind_mlir_aie_cpp_uint8(py::module& m)
{

    using mlir_aie_cpp_uint8    = gr::mlir_aie::mlir_aie_cpp_uint8;


    py::class_<mlir_aie_cpp_uint8, gr::block, gr::basic_block,
        std::shared_ptr<mlir_aie_cpp_uint8>>(m, "mlir_aie_cpp_uint8", D(mlir_aie_cpp_uint8))

        .def(py::init(&mlir_aie_cpp_uint8::make),
           D(mlir_aie_cpp_uint8,make)
        )
        



        ;




}








