/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mlire_aie_cpp_int32_to_int16.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b5965fe81d7e71e53a6d61631c8857b1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mlir_aie/mlire_aie_cpp_int32_to_int16.h>
// pydoc.h is automatically generated in the build directory
#include <mlire_aie_cpp_int32_to_int16_pydoc.h>

void bind_mlire_aie_cpp_int32_to_int16(py::module& m)
{

    using mlire_aie_cpp_int32_to_int16    = gr::mlir_aie::mlire_aie_cpp_int32_to_int16;


    py::class_<mlire_aie_cpp_int32_to_int16, gr::block, gr::basic_block,
        std::shared_ptr<mlire_aie_cpp_int32_to_int16>>(m, "mlire_aie_cpp_int32_to_int16", D(mlire_aie_cpp_int32_to_int16))

        .def(py::init(&mlire_aie_cpp_int32_to_int16::make),
           D(mlire_aie_cpp_int32_to_int16,make)
        )
        



        ;




}








